algorithm: fixmatch
save_dir: ./saved_models
resume: True
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 25600
num_warmup_iter: 0
num_log_iter: 256
num_eval_iter: 2048
num_labels: 20
batch_size: 16
eval_batch_size: 16
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 1
use_cat: False
ema_m: 0.0
optim: AdamW
lr: 2e-05
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.75
amp: False
clip: 0.0
net: roberta_base
net_from_name: False
data_dir: ./data
dataset: aclImdb
train_sampler: RandomSampler
num_classes: 2
num_workers: 4
max_length: 256
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10007
dist_backend: nccl
gpu: None
