algorithm: uda
save_dir: ./saved_models
# save_name: uda_yahoo_answers_500_0
resume: True
# load_path: ./saved_models/usb_nlp/uda_yahoo_answers_500_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 25600
num_warmup_iter: 0
num_log_iter: 256
num_eval_iter: 2048
num_labels: 500
batch_size: 16
eval_batch_size: 16
tsa_schedule: exp
T: 0.4
p_cutoff: 0.8
ulb_loss_ratio: 1.0
uratio: 1
use_cat: False
ema_m: 0.0
optim: AdamW
lr: 2e-05
momentum: 0.9
weight_decay: 0.0005
layer_decay: 0.65
amp: False
clip: 0.0
net: roberta_base
net_from_name: False
data_dir: ./data
dataset: yahoo_answers
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
max_length: 256
# seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10017
dist_backend: nccl
gpu: None
